# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_tx/fifo_gtx_tx.xci
# IP: The module: 'fifo_gtx_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_tx/fifo_gtx_tx/fifo_gtx_tx_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gtx_tx'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_tx/fifo_gtx_tx/fifo_gtx_tx.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gtx_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_tx/fifo_gtx_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gtx_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_tx/fifo_gtx_tx.xci
# IP: The module: 'fifo_gtx_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_tx/fifo_gtx_tx/fifo_gtx_tx_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gtx_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_tx/fifo_gtx_tx/fifo_gtx_tx.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gtx_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_tx/fifo_gtx_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gtx_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
