# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/constraints.xdc

# Block Designs: bd/v7_bd/v7_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd || ORIG_REF_NAME==v7_bd}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_0_0/v7_bd_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_0_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_drp_0/v7_bd_axi_bram_ctrl_drp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_drp_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_drp_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_gth_reg_file_0/v7_bd_axi_bram_ctrl_gth_reg_file_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_gth_reg_file_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_gth_reg_file_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_reg_file_0/v7_bd_axi_bram_ctrl_reg_file_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_reg_file_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_reg_file_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_rx_ram_0/v7_bd_axi_bram_ctrl_rx_ram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_rx_ram_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_rx_ram_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_tx_ram_0/v7_bd_axi_bram_ctrl_tx_ram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_tx_ram_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_tx_ram_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_interconnect_0_0/v7_bd_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_interconnect_0_0 || ORIG_REF_NAME==v7_bd_axi_interconnect_0_0}]

# IP: bd/v7_bd/ip/v7_bd_blk_mem_gen_0_0/v7_bd_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==v7_bd_blk_mem_gen_0_0}]

# IP: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}]

# IP: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0}]

# IP: bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_xadc_wiz_0_0 || ORIG_REF_NAME==v7_bd_xadc_wiz_0_0}]

# IP: bd/v7_bd/ip/v7_bd_xbar_0/v7_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_xbar_0 || ORIG_REF_NAME==v7_bd_xbar_0}]

# IP: bd/v7_bd/ip/v7_bd_registers_0_0/v7_bd_registers_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_registers_0_0 || ORIG_REF_NAME==v7_bd_registers_0_0}]

# IP: bd/v7_bd/ip/v7_bd_registers_0_0/src/ila_axi_regs/ila_axi_regs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_axi_regs || ORIG_REF_NAME==ila_axi_regs}]

# IP: bd/v7_bd/ip/v7_bd_registers_0_0/src/vio_regs/vio_regs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_regs || ORIG_REF_NAME==vio_regs}]

# IP: bd/v7_bd/ip/v7_bd_registers_0_0/src/fifo_axi_write_cmds/fifo_axi_write_cmds.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_write_cmds || ORIG_REF_NAME==fifo_axi_write_cmds}]

# IP: bd/v7_bd/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_auto_pc_0 || ORIG_REF_NAME==v7_bd_auto_pc_0}]

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_0_0/v7_bd_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_drp_0/v7_bd_axi_bram_ctrl_drp_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_gth_reg_file_0/v7_bd_axi_bram_ctrl_gth_reg_file_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_reg_file_0/v7_bd_axi_bram_ctrl_reg_file_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_rx_ram_0/v7_bd_axi_bram_ctrl_rx_ram_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_tx_ram_0/v7_bd_axi_bram_ctrl_tx_ram_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_blk_mem_gen_0_0/v7_bd_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0}]

# XDC: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0}]

# XDC: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_xadc_wiz_0_0 || ORIG_REF_NAME==v7_bd_xadc_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/v7_bd/ip/v7_bd_xbar_0/v7_bd_xbar_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_registers_0_0/src/ila_axi_regs/ila_v6_0/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_axi_regs || ORIG_REF_NAME==ila_axi_regs}]

# XDC: bd/v7_bd/ip/v7_bd_registers_0_0/src/ila_axi_regs/ila_axi_regs_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_registers_0_0/src/vio_regs/vio_regs.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_regs || ORIG_REF_NAME==vio_regs}]

# XDC: bd/v7_bd/ip/v7_bd_registers_0_0/src/vio_regs/vio_regs_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_registers_0_0/src/fifo_axi_write_cmds/fifo_axi_write_cmds/fifo_axi_write_cmds_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_write_cmds || ORIG_REF_NAME==fifo_axi_write_cmds}] {/U0 }]/U0 ]]

# XDC: bd/v7_bd/ip/v7_bd_registers_0_0/src/fifo_axi_write_cmds/fifo_axi_write_cmds/fifo_axi_write_cmds.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_write_cmds || ORIG_REF_NAME==fifo_axi_write_cmds}] {/U0 }]/U0 ]]

# XDC: bd/v7_bd/ip/v7_bd_registers_0_0/src/fifo_axi_write_cmds/fifo_axi_write_cmds_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0_ooc.xdc

# XDC: bd/v7_bd/v7_bd_ooc.xdc
