# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/constraints.xdc

# Block Designs: bd/v7_bd/v7_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd || ORIG_REF_NAME==v7_bd}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_0_0/v7_bd_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_0_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_drp_0/v7_bd_axi_bram_ctrl_drp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_drp_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_drp_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_gth_reg_file_0/v7_bd_axi_bram_ctrl_gth_reg_file_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_gth_reg_file_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_gth_reg_file_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_reg_file_0/v7_bd_axi_bram_ctrl_reg_file_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_reg_file_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_reg_file_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_rx_ram_0/v7_bd_axi_bram_ctrl_rx_ram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_rx_ram_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_rx_ram_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_tx_ram_0/v7_bd_axi_bram_ctrl_tx_ram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_tx_ram_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_tx_ram_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_interconnect_0_0/v7_bd_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_interconnect_0_0 || ORIG_REF_NAME==v7_bd_axi_interconnect_0_0}]

# IP: bd/v7_bd/ip/v7_bd_xbar_0/v7_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_xbar_0 || ORIG_REF_NAME==v7_bd_xbar_0}]

# IP: bd/v7_bd/ip/v7_bd_blk_mem_gen_0_0/v7_bd_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==v7_bd_blk_mem_gen_0_0}]

# IP: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}]

# IP: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0}]

# IP: bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_xadc_wiz_0_0 || ORIG_REF_NAME==v7_bd_xadc_wiz_0_0}]

# IP: bd/v7_bd/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_auto_pc_0 || ORIG_REF_NAME==v7_bd_auto_pc_0}]

# IP: bd/v7_bd/ip/v7_bd_auto_pc_1/v7_bd_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_auto_pc_1 || ORIG_REF_NAME==v7_bd_auto_pc_1}]

# IP: bd/v7_bd/ip/v7_bd_auto_pc_2/v7_bd_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_auto_pc_2 || ORIG_REF_NAME==v7_bd_auto_pc_2}]

# IP: bd/v7_bd/ip/v7_bd_auto_pc_3/v7_bd_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_auto_pc_3 || ORIG_REF_NAME==v7_bd_auto_pc_3}]

# IP: bd/v7_bd/ip/v7_bd_auto_pc_4/v7_bd_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_auto_pc_4 || ORIG_REF_NAME==v7_bd_auto_pc_4}]

# IP: bd/v7_bd/ip/v7_bd_auto_pc_5/v7_bd_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_auto_pc_5 || ORIG_REF_NAME==v7_bd_auto_pc_5}]

# IP: bd/v7_bd/ip/v7_bd_auto_pc_6/v7_bd_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_auto_pc_6 || ORIG_REF_NAME==v7_bd_auto_pc_6}]

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_0_0/v7_bd_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_drp_0/v7_bd_axi_bram_ctrl_drp_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_gth_reg_file_0/v7_bd_axi_bram_ctrl_gth_reg_file_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_reg_file_0/v7_bd_axi_bram_ctrl_reg_file_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_rx_ram_0/v7_bd_axi_bram_ctrl_rx_ram_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_tx_ram_0/v7_bd_axi_bram_ctrl_tx_ram_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_xbar_0/v7_bd_xbar_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_blk_mem_gen_0_0/v7_bd_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0}]

# XDC: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0}]

# XDC: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_xadc_wiz_0_0 || ORIG_REF_NAME==v7_bd_xadc_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/v7_bd/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_auto_pc_1/v7_bd_auto_pc_1_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_auto_pc_2/v7_bd_auto_pc_2_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_auto_pc_3/v7_bd_auto_pc_3_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_auto_pc_4/v7_bd_auto_pc_4_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_auto_pc_5/v7_bd_auto_pc_5_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_auto_pc_6/v7_bd_auto_pc_6_ooc.xdc

# XDC: bd/v7_bd/v7_bd_ooc.xdc
