# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.cache/wt [current_project]
set_property parent.project_path /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/evka/code/ip_repo/myip_1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/tamu_ctp7_v7/tamu_ctp7_v7.srcs/playback_capture_ram/ip/playback_capture_ram/pb_cap_ram.coe
add_files -quiet /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.runs/ila_4p8g_synth_1/ila_4p8g.dcp
set_property used_in_implementation false [get_files /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.runs/ila_4p8g_synth_1/ila_4p8g.dcp]
add_files -quiet /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.runs/vio_4p8g_synth_1/vio_4p8g.dcp
set_property used_in_implementation false [get_files /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.runs/vio_4p8g_synth_1/vio_4p8g.dcp]
add_files -quiet /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.runs/fifo_gtx_tx_synth_1/fifo_gtx_tx.dcp
set_property used_in_implementation false [get_files /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.runs/fifo_gtx_tx_synth_1/fifo_gtx_tx.dcp]
add_files -quiet /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.runs/fifo_gtx_rx_synth_1/fifo_gtx_rx.dcp
set_property used_in_implementation false [get_files /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.runs/fifo_gtx_rx_synth_1/fifo_gtx_rx.dcp]
add_files /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/v7_bd.bd
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_bram_ctrl_0_0/v7_bd_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_bram_ctrl_drp_0/v7_bd_axi_bram_ctrl_drp_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_bram_ctrl_gth_reg_file_0/v7_bd_axi_bram_ctrl_gth_reg_file_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_bram_ctrl_reg_file_0/v7_bd_axi_bram_ctrl_reg_file_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_bram_ctrl_rx_ram_0/v7_bd_axi_bram_ctrl_rx_ram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_bram_ctrl_tx_ram_0/v7_bd_axi_bram_ctrl_tx_ram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_xbar_0/v7_bd_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_blk_mem_gen_0_0/v7_bd_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_auto_pc_1/v7_bd_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_auto_pc_2/v7_bd_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_auto_pc_3/v7_bd_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_auto_pc_4/v7_bd_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_auto_pc_5/v7_bd_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_auto_pc_6/v7_bd_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/v7_bd_ooc.xdc]
set_property is_locked true [get_files /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/v7_bd.bd]

read_vhdl -library xil_defaultlib {
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/TTC_decoder.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_single_sync_pulse.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_single_sync_block.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/tamu_ctp7_v7_build_cfg.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_4p8_raw_CLOCK_MODULE.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_pkg.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/gem/gem_pkg.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/gem/link/link_tx_tracking.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/gem/link/link_rx_tracking.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/ttc_pkg.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/ctp7_utils_pkg.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/capture_playback_pkg.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/ttc_cmd.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/pulse_extend.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/ctp7_ttc_clocks.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_single_TX_STARTUP_FSM.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_single_TX_MANUAL_PHASE_ALIGN.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_single_RX_STARTUP_FSM.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_single_AUTO_PHASE_ALIGN.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_single_4p8g.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_single_3p2g.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_clk_bufs.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/gem/link/optohybrid_single.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/register_file.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_register_file.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/drp_controller.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/ctp7_ttc.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/io_link_4p8g_demo_ctrl.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/gth_wrapper.vhd
  /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/imports/new/tamu_ctp7_v7.vhd
}
read_xdc /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/constrs_1/imports/new/constraints.xdc
set_property used_in_implementation false [get_files /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/constrs_1/imports/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top tamu_ctp7_v7 -part xc7vx690tffg1927-2
write_checkpoint -noxdef tamu_ctp7_v7.dcp
catch { report_utilization -file tamu_ctp7_v7_utilization_synth.rpt -pb tamu_ctp7_v7_utilization_synth.pb }
