# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/evka/code/tamu_ctp7_v7/ip/edit_registers_v1_0.cache/wt [current_project]
set_property parent.project_path /home/evka/code/tamu_ctp7_v7/ip/edit_registers_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/evka/code/tamu_ctp7_v7/ip/registers_1.0
  /home/evka/code/ip_repo/myip_1.0
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs.xci
set_property used_in_implementation false [get_files -all /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs.dcp]
set_property is_locked true [get_files /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs.xci]

synth_design -top ila_axi_regs -part xc7vx690tffg1927-2 -mode out_of_context
rename_ref -prefix_all ila_axi_regs_
write_checkpoint -noxdef ila_axi_regs.dcp
catch { report_utilization -file ila_axi_regs_utilization_synth.rpt -pb ila_axi_regs_utilization_synth.pb }
if { [catch {
  file copy -force /home/evka/code/tamu_ctp7_v7/ip/edit_registers_v1_0.runs/ila_axi_regs_synth_1/ila_axi_regs.dcp /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/evka/code/tamu_ctp7_v7/ip/edit_registers_v1_0.ip_user_files/ip/ila_axi_regs]} {
  catch { 
    file copy -force /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs_stub.v /home/evka/code/tamu_ctp7_v7/ip/edit_registers_v1_0.ip_user_files/ip/ila_axi_regs
  }
}

if {[file isdir /home/evka/code/tamu_ctp7_v7/ip/edit_registers_v1_0.ip_user_files/ip/ila_axi_regs]} {
  catch { 
    file copy -force /home/evka/code/tamu_ctp7_v7/ip/registers_1.0/src/ila_axi_regs/ila_axi_regs_stub.vhdl /home/evka/code/tamu_ctp7_v7/ip/edit_registers_v1_0.ip_user_files/ip/ila_axi_regs
  }
}
