# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.cache/wt [current_project]
set_property parent.project_path /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  /home/evka/code/tamu_ctp7_v7/ip/registers_1.0
  /home/evka/code/ip_repo/myip_1.0
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_rx/fifo_gtx_rx.xci
set_property is_locked true [get_files /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_rx/fifo_gtx_rx.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top fifo_gtx_rx -part xc7vx690tffg1927-2 -mode out_of_context
rename_ref -prefix_all fifo_gtx_rx_
write_checkpoint -noxdef fifo_gtx_rx.dcp
catch { report_utilization -file fifo_gtx_rx_utilization_synth.rpt -pb fifo_gtx_rx_utilization_synth.pb }
if { [catch {
  file copy -force /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.runs/fifo_gtx_rx_synth_1/fifo_gtx_rx.dcp /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_rx/fifo_gtx_rx.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_rx/fifo_gtx_rx_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_rx/fifo_gtx_rx_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_rx/fifo_gtx_rx_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_rx/fifo_gtx_rx_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.ip_user_files/ip/fifo_gtx_rx]} {
  catch { 
    file copy -force /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_rx/fifo_gtx_rx_stub.v /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.ip_user_files/ip/fifo_gtx_rx
  }
}

if {[file isdir /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.ip_user_files/ip/fifo_gtx_rx]} {
  catch { 
    file copy -force /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/ip/fifo_gtx_rx/fifo_gtx_rx_stub.vhdl /home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.ip_user_files/ip/fifo_gtx_rx
  }
}
