set_property SRC_FILE_INFO {cfile:/home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xdc rfile:../../../tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xdc id:1 order:EARLY scoped_inst:i_v7_bd/axi_chip2chip_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xdc rfile:../../../tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xdc id:2 order:EARLY scoped_inst:i_v7_bd/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/constrs_1/imports/new/constraints.xdc rfile:../../../tamu_ctp7_v7.srcs/constrs_1/imports/new/constraints.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/evka/code/tamu_ctp7_v7/tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_clocks.xdc rfile:../../../tamu_ctp7_v7.srcs/sources_1/bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_clocks.xdc id:4 order:LATE scoped_inst:i_v7_bd/axi_chip2chip_0/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins slave_fpga_gen.axi_chip2chip_slave_phy_inst/slave_sio_phy.rx_reset_sync_inst/sync_reset_out_reg/C] -datapath_only 5.000
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/calib_error_flop_reg/C] -to [get_pins slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/axi_chip2chip_sync_cell_inst/sync_flop_0_reg[1]/D] -datapath_only 5.000
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1_p]] 0.05
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H29 [get_ports clk_200_diff_in_clk_n]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {LEDs[0]}]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports {LEDs[1]}]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV30 [get_ports clk_40_ttc_n_i]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J26 [get_ports ttc_data_n_i]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD31 [get_ports axi_c2c_v7_to_zynq_clk]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY32 [get_ports {axi_c2c_v7_to_zynq_data[0]}]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA33 [get_ports {axi_c2c_v7_to_zynq_data[1]}]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR31 [get_ports {axi_c2c_v7_to_zynq_data[2]}]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR32 [get_ports {axi_c2c_v7_to_zynq_data[3]}]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV32 [get_ports {axi_c2c_v7_to_zynq_data[4]}]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW32 [get_ports {axi_c2c_v7_to_zynq_data[5]}]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ30 [get_ports {axi_c2c_v7_to_zynq_data[6]}]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ31 [get_ports {axi_c2c_v7_to_zynq_data[7]}]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM32 [get_ports {axi_c2c_v7_to_zynq_data[8]}]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM33 [get_ports {axi_c2c_v7_to_zynq_data[9]}]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB33 [get_ports {axi_c2c_v7_to_zynq_data[10]}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV33 [get_ports {axi_c2c_v7_to_zynq_data[11]}]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP32 [get_ports {axi_c2c_v7_to_zynq_data[12]}]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN32 [get_ports {axi_c2c_v7_to_zynq_data[13]}]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC34 [get_ports {axi_c2c_v7_to_zynq_data[14]}]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU33 [get_ports axi_c2c_zynq_to_v7_clk]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV34 [get_ports {axi_c2c_zynq_to_v7_data[0]}]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV35 [get_ports {axi_c2c_zynq_to_v7_data[1]}]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW34 [get_ports {axi_c2c_zynq_to_v7_data[2]}]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW35 [get_ports {axi_c2c_zynq_to_v7_data[3]}]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY33 [get_ports {axi_c2c_zynq_to_v7_data[4]}]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY34 [get_ports {axi_c2c_zynq_to_v7_data[5]}]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA34 [get_ports {axi_c2c_zynq_to_v7_data[6]}]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA35 [get_ports {axi_c2c_zynq_to_v7_data[7]}]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD34 [get_ports {axi_c2c_zynq_to_v7_data[8]}]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD35 [get_ports {axi_c2c_zynq_to_v7_data[9]}]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB35 [get_ports {axi_c2c_zynq_to_v7_data[10]}]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC35 [get_ports {axi_c2c_zynq_to_v7_data[11]}]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC32 [get_ports {axi_c2c_zynq_to_v7_data[12]}]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC33 [get_ports {axi_c2c_zynq_to_v7_data[13]}]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD32 [get_ports {axi_c2c_zynq_to_v7_data[14]}]
set_property src_info {type:XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB31 [get_ports axi_c2c_zynq_to_v7_reset]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB32 [get_ports axi_c2c_v7_to_zynq_link_status]
set_property src_info {type:XDC file:3 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E10 [get_ports {refclk_F_0_p_i[0]}]
set_property src_info {type:XDC file:3 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N10 [get_ports {refclk_F_0_p_i[1]}]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF8 [get_ports {refclk_F_0_p_i[2]}]
set_property src_info {type:XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR10 [get_ports {refclk_F_0_p_i[3]}]
set_property src_info {type:XDC file:3 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports {refclk_F_1_p_i[0]}]
set_property src_info {type:XDC file:3 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R10 [get_ports {refclk_F_1_p_i[1]}]
set_property src_info {type:XDC file:3 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH8 [get_ports {refclk_F_1_p_i[2]}]
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT8 [get_ports {refclk_F_1_p_i[3]}]
set_property src_info {type:XDC file:3 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF37 [get_ports {refclk_B_0_p_i[1]}]
set_property src_info {type:XDC file:3 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N35 [get_ports {refclk_B_0_p_i[2]}]
set_property src_info {type:XDC file:3 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E35 [get_ports {refclk_B_0_p_i[3]}]
set_property src_info {type:XDC file:3 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH37 [get_ports {refclk_B_1_p_i[1]}]
set_property src_info {type:XDC file:3 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R35 [get_ports {refclk_B_1_p_i[2]}]
set_property src_info {type:XDC file:3 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G35 [get_ports {refclk_B_1_p_i[3]}]
set_property src_info {type:XDC file:3 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y0 [get_cells {i_gth_wrapper/gen_gth_single[0].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y1 [get_cells {i_gth_wrapper/gen_gth_single[1].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y2 [get_cells {i_gth_wrapper/gen_gth_single[2].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y3 [get_cells {i_gth_wrapper/gen_gth_single[3].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y4 [get_cells {i_gth_wrapper/gen_gth_single[4].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y5 [get_cells {i_gth_wrapper/gen_gth_single[5].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y6 [get_cells {i_gth_wrapper/gen_gth_single[6].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y7 [get_cells {i_gth_wrapper/gen_gth_single[7].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y8 [get_cells {i_gth_wrapper/gen_gth_single[8].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y9 [get_cells {i_gth_wrapper/gen_gth_single[9].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y10 [get_cells {i_gth_wrapper/gen_gth_single[10].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y11 [get_cells {i_gth_wrapper/gen_gth_single[11].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells {i_gth_wrapper/gen_gth_single[12].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y13 [get_cells {i_gth_wrapper/gen_gth_single[13].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y14 [get_cells {i_gth_wrapper/gen_gth_single[14].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y15 [get_cells {i_gth_wrapper/gen_gth_single[15].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y16 [get_cells {i_gth_wrapper/gen_gth_single[16].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y17 [get_cells {i_gth_wrapper/gen_gth_single[17].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y18 [get_cells {i_gth_wrapper/gen_gth_single[18].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y19 [get_cells {i_gth_wrapper/gen_gth_single[19].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y20 [get_cells {i_gth_wrapper/gen_gth_single[20].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y21 [get_cells {i_gth_wrapper/gen_gth_single[21].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y22 [get_cells {i_gth_wrapper/gen_gth_single[22].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y23 [get_cells {i_gth_wrapper/gen_gth_single[23].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y24 [get_cells {i_gth_wrapper/gen_gth_single[24].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y25 [get_cells {i_gth_wrapper/gen_gth_single[25].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y26 [get_cells {i_gth_wrapper/gen_gth_single[26].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y27 [get_cells {i_gth_wrapper/gen_gth_single[27].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y28 [get_cells {i_gth_wrapper/gen_gth_single[28].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y29 [get_cells {i_gth_wrapper/gen_gth_single[29].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y30 [get_cells {i_gth_wrapper/gen_gth_single[30].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y31 [get_cells {i_gth_wrapper/gen_gth_single[31].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y32 [get_cells {i_gth_wrapper/gen_gth_single[32].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y33 [get_cells {i_gth_wrapper/gen_gth_single[33].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y34 [get_cells {i_gth_wrapper/gen_gth_single[34].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y35 [get_cells {i_gth_wrapper/gen_gth_single[35].gen_gth_*/i_gthe2}]
set_property src_info {type:XDC file:3 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC XADC_X0Y0 [get_cells i_v7_bd/xadc_wiz_0/U0/AXI_XADC_CORE_I/XADC_INST]
set_property src_info {type:XDC file:3 line:428 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:3 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:3 line:438 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list {i_gth_wrapper/i_gth_clk_bufs/clk_gth_rx_usrclk_arr_o[6]}]]
set_property src_info {type:XDC file:3 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:441 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {s_gth_rx_data_arr[6][rxnotintable][0]} {s_gth_rx_data_arr[6][rxnotintable][1]} {s_gth_rx_data_arr[6][rxnotintable][2]} {s_gth_rx_data_arr[6][rxnotintable][3]}]]
set_property src_info {type:XDC file:3 line:442 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:3 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:3 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:3 line:452 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list {oh_reg_request_arr[6][axi_reg_clk]}]]
set_property src_info {type:XDC file:3 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:3 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:3 line:455 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {oh_reg_response_arr[6][data][0]} {oh_reg_response_arr[6][data][1]} {oh_reg_response_arr[6][data][2]} {oh_reg_response_arr[6][data][3]} {oh_reg_response_arr[6][data][4]} {oh_reg_response_arr[6][data][5]} {oh_reg_response_arr[6][data][6]} {oh_reg_response_arr[6][data][7]} {oh_reg_response_arr[6][data][8]} {oh_reg_response_arr[6][data][9]} {oh_reg_response_arr[6][data][10]} {oh_reg_response_arr[6][data][11]} {oh_reg_response_arr[6][data][12]} {oh_reg_response_arr[6][data][13]} {oh_reg_response_arr[6][data][14]} {oh_reg_response_arr[6][data][15]} {oh_reg_response_arr[6][data][16]} {oh_reg_response_arr[6][data][17]} {oh_reg_response_arr[6][data][18]} {oh_reg_response_arr[6][data][19]} {oh_reg_response_arr[6][data][20]} {oh_reg_response_arr[6][data][21]} {oh_reg_response_arr[6][data][22]} {oh_reg_response_arr[6][data][23]} {oh_reg_response_arr[6][data][24]} {oh_reg_response_arr[6][data][25]} {oh_reg_response_arr[6][data][26]} {oh_reg_response_arr[6][data][27]} {oh_reg_response_arr[6][data][28]} {oh_reg_response_arr[6][data][29]} {oh_reg_response_arr[6][data][30]} {oh_reg_response_arr[6][data][31]}]]
set_property src_info {type:XDC file:3 line:456 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_2 ila
set_property src_info {type:XDC file:3 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:3 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
set_property src_info {type:XDC file:3 line:466 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list {s_clk_gth_tx_usrclk_arr[6]}]]
set_property src_info {type:XDC file:3 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:3 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:3 line:469 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list {s_gth_tx_data_arr[6][txdata][0]} {s_gth_tx_data_arr[6][txdata][1]} {s_gth_tx_data_arr[6][txdata][2]} {s_gth_tx_data_arr[6][txdata][3]} {s_gth_tx_data_arr[6][txdata][4]} {s_gth_tx_data_arr[6][txdata][5]} {s_gth_tx_data_arr[6][txdata][6]} {s_gth_tx_data_arr[6][txdata][7]} {s_gth_tx_data_arr[6][txdata][8]} {s_gth_tx_data_arr[6][txdata][9]} {s_gth_tx_data_arr[6][txdata][10]} {s_gth_tx_data_arr[6][txdata][11]} {s_gth_tx_data_arr[6][txdata][12]} {s_gth_tx_data_arr[6][txdata][13]} {s_gth_tx_data_arr[6][txdata][14]} {s_gth_tx_data_arr[6][txdata][15]} {s_gth_tx_data_arr[6][txdata][16]} {s_gth_tx_data_arr[6][txdata][17]} {s_gth_tx_data_arr[6][txdata][18]} {s_gth_tx_data_arr[6][txdata][19]} {s_gth_tx_data_arr[6][txdata][20]} {s_gth_tx_data_arr[6][txdata][21]} {s_gth_tx_data_arr[6][txdata][22]} {s_gth_tx_data_arr[6][txdata][23]} {s_gth_tx_data_arr[6][txdata][24]} {s_gth_tx_data_arr[6][txdata][25]} {s_gth_tx_data_arr[6][txdata][26]} {s_gth_tx_data_arr[6][txdata][27]} {s_gth_tx_data_arr[6][txdata][28]} {s_gth_tx_data_arr[6][txdata][29]} {s_gth_tx_data_arr[6][txdata][30]} {s_gth_tx_data_arr[6][txdata][31]}]]
set_property src_info {type:XDC file:3 line:470 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:473 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {s_gth_rx_data_arr[6][rxdisperr][0]} {s_gth_rx_data_arr[6][rxdisperr][1]} {s_gth_rx_data_arr[6][rxdisperr][2]} {s_gth_rx_data_arr[6][rxdisperr][3]}]]
set_property src_info {type:XDC file:3 line:474 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:477 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {s_gth_rx_data_arr[6][rxdata][0]} {s_gth_rx_data_arr[6][rxdata][1]} {s_gth_rx_data_arr[6][rxdata][2]} {s_gth_rx_data_arr[6][rxdata][3]} {s_gth_rx_data_arr[6][rxdata][4]} {s_gth_rx_data_arr[6][rxdata][5]} {s_gth_rx_data_arr[6][rxdata][6]} {s_gth_rx_data_arr[6][rxdata][7]} {s_gth_rx_data_arr[6][rxdata][8]} {s_gth_rx_data_arr[6][rxdata][9]} {s_gth_rx_data_arr[6][rxdata][10]} {s_gth_rx_data_arr[6][rxdata][11]} {s_gth_rx_data_arr[6][rxdata][12]} {s_gth_rx_data_arr[6][rxdata][13]} {s_gth_rx_data_arr[6][rxdata][14]} {s_gth_rx_data_arr[6][rxdata][15]} {s_gth_rx_data_arr[6][rxdata][16]} {s_gth_rx_data_arr[6][rxdata][17]} {s_gth_rx_data_arr[6][rxdata][18]} {s_gth_rx_data_arr[6][rxdata][19]} {s_gth_rx_data_arr[6][rxdata][20]} {s_gth_rx_data_arr[6][rxdata][21]} {s_gth_rx_data_arr[6][rxdata][22]} {s_gth_rx_data_arr[6][rxdata][23]} {s_gth_rx_data_arr[6][rxdata][24]} {s_gth_rx_data_arr[6][rxdata][25]} {s_gth_rx_data_arr[6][rxdata][26]} {s_gth_rx_data_arr[6][rxdata][27]} {s_gth_rx_data_arr[6][rxdata][28]} {s_gth_rx_data_arr[6][rxdata][29]} {s_gth_rx_data_arr[6][rxdata][30]} {s_gth_rx_data_arr[6][rxdata][31]}]]
set_property src_info {type:XDC file:3 line:478 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:481 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {s_gth_rx_data_arr[6][rxcharisk][0]} {s_gth_rx_data_arr[6][rxcharisk][1]} {s_gth_rx_data_arr[6][rxcharisk][2]} {s_gth_rx_data_arr[6][rxcharisk][3]}]]
set_property src_info {type:XDC file:3 line:482 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:485 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {s_gth_rx_data_arr[6][rxchariscomma][0]} {s_gth_rx_data_arr[6][rxchariscomma][1]} {s_gth_rx_data_arr[6][rxchariscomma][2]} {s_gth_rx_data_arr[6][rxchariscomma][3]}]]
set_property src_info {type:XDC file:3 line:486 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:489 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {s_gth_rx_data_arr[6][rxbyteisaligned]}]]
set_property src_info {type:XDC file:3 line:490 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:493 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {s_gth_rx_data_arr[6][rxbyterealign]}]]
set_property src_info {type:XDC file:3 line:494 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:497 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {s_gth_rx_data_arr[6][rxcommadet]}]]
set_property src_info {type:XDC file:3 line:498 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:3 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:3 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:3 line:501 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list {oh_reg_request_arr[6][data][0]} {oh_reg_request_arr[6][data][1]} {oh_reg_request_arr[6][data][2]} {oh_reg_request_arr[6][data][3]} {oh_reg_request_arr[6][data][4]} {oh_reg_request_arr[6][data][5]} {oh_reg_request_arr[6][data][6]} {oh_reg_request_arr[6][data][7]} {oh_reg_request_arr[6][data][8]} {oh_reg_request_arr[6][data][9]} {oh_reg_request_arr[6][data][10]} {oh_reg_request_arr[6][data][11]} {oh_reg_request_arr[6][data][12]} {oh_reg_request_arr[6][data][13]} {oh_reg_request_arr[6][data][14]} {oh_reg_request_arr[6][data][15]} {oh_reg_request_arr[6][data][16]} {oh_reg_request_arr[6][data][17]} {oh_reg_request_arr[6][data][18]} {oh_reg_request_arr[6][data][19]} {oh_reg_request_arr[6][data][20]} {oh_reg_request_arr[6][data][21]} {oh_reg_request_arr[6][data][22]} {oh_reg_request_arr[6][data][23]} {oh_reg_request_arr[6][data][24]} {oh_reg_request_arr[6][data][25]} {oh_reg_request_arr[6][data][26]} {oh_reg_request_arr[6][data][27]} {oh_reg_request_arr[6][data][28]} {oh_reg_request_arr[6][data][29]} {oh_reg_request_arr[6][data][30]} {oh_reg_request_arr[6][data][31]}]]
set_property src_info {type:XDC file:3 line:502 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:3 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:3 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:3 line:505 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list {oh_reg_request_arr[6][addr][0]} {oh_reg_request_arr[6][addr][1]} {oh_reg_request_arr[6][addr][2]} {oh_reg_request_arr[6][addr][3]} {oh_reg_request_arr[6][addr][4]} {oh_reg_request_arr[6][addr][5]} {oh_reg_request_arr[6][addr][6]} {oh_reg_request_arr[6][addr][7]} {oh_reg_request_arr[6][addr][8]} {oh_reg_request_arr[6][addr][9]} {oh_reg_request_arr[6][addr][10]} {oh_reg_request_arr[6][addr][11]} {oh_reg_request_arr[6][addr][12]} {oh_reg_request_arr[6][addr][13]} {oh_reg_request_arr[6][addr][14]} {oh_reg_request_arr[6][addr][15]} {oh_reg_request_arr[6][addr][16]} {oh_reg_request_arr[6][addr][17]} {oh_reg_request_arr[6][addr][18]} {oh_reg_request_arr[6][addr][19]} {oh_reg_request_arr[6][addr][20]} {oh_reg_request_arr[6][addr][21]} {oh_reg_request_arr[6][addr][22]} {oh_reg_request_arr[6][addr][23]} {oh_reg_request_arr[6][addr][24]} {oh_reg_request_arr[6][addr][25]} {oh_reg_request_arr[6][addr][26]} {oh_reg_request_arr[6][addr][27]} {oh_reg_request_arr[6][addr][28]} {oh_reg_request_arr[6][addr][29]} {oh_reg_request_arr[6][addr][30]} {oh_reg_request_arr[6][addr][31]}]]
set_property src_info {type:XDC file:3 line:506 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:3 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:3 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:3 line:509 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe3 [get_nets [list {oh_reg_request_arr[6][en]}]]
set_property src_info {type:XDC file:3 line:510 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:3 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:3 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:3 line:513 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe4 [get_nets [list {oh_reg_request_arr[6][we]}]]
set_property src_info {type:XDC file:3 line:514 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:3 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:3 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:3 line:517 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe5 [get_nets [list {oh_reg_response_arr[6][en]}]]
set_property src_info {type:XDC file:3 line:518 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:3 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:3 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:3 line:521 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe1 [get_nets [list {s_gth_tx_data_arr[6][txcharisk][0]} {s_gth_tx_data_arr[6][txcharisk][1]} {s_gth_tx_data_arr[6][txcharisk][2]} {s_gth_tx_data_arr[6][txcharisk][3]}]]
set_property src_info {type:XDC file:3 line:522 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:3 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property src_info {type:XDC file:3 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_2/probe2]
set_property src_info {type:XDC file:3 line:525 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe2 [get_nets [list {s_gth_tx_data_arr[6][txchardispval][0]} {s_gth_tx_data_arr[6][txchardispval][1]} {s_gth_tx_data_arr[6][txchardispval][2]} {s_gth_tx_data_arr[6][txchardispval][3]}]]
set_property src_info {type:XDC file:3 line:526 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:3 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property src_info {type:XDC file:3 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_2/probe3]
set_property src_info {type:XDC file:3 line:529 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe3 [get_nets [list {s_gth_tx_data_arr[6][txchardispmode][0]} {s_gth_tx_data_arr[6][txchardispmode][1]} {s_gth_tx_data_arr[6][txchardispmode][2]} {s_gth_tx_data_arr[6][txchardispmode][3]}]]
set_property src_info {type:XDC file:3 line:530 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:533 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {oh_reg_request_arr[7][en]}]]
set_property src_info {type:XDC file:3 line:534 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:3 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property src_info {type:XDC file:3 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe4]
set_property src_info {type:XDC file:3 line:537 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe4 [get_nets [list {oh_reg_request_arr[8][en]}]]
set_property src_info {type:XDC file:3 line:538 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:541 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {oh_reg_response_arr[7][en]}]]
set_property src_info {type:XDC file:3 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:545 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets BRAM_CTRL_DRP_clk]
set_property src_info {type:SCOPED_XDC file:4 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only 5.0
set_property src_info {type:SCOPED_XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only 5.0
set_property src_info {type:SCOPED_XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to  [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only 5.0
set_property src_info {type:SCOPED_XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_v7_bd/axi_chip2chip_0/inst/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]]  -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_v7_bd/axi_chip2chip_0/inst/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]]  -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_v7_bd/axi_chip2chip_0/inst/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to  [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]]   -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_v7_bd/axi_chip2chip_0/inst/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]]  -datapath_only 5.0
set_property src_info {type:SCOPED_XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_v7_bd/axi_chip2chip_0/inst/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]]  -datapath_only 5.0
set_property src_info {type:SCOPED_XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports m_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_pins -hier *mmcm_adv_inst/CLKOUT0] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports m_axi_lite_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_v7_bd/axi_chip2chip_0/inst/m_axi_lite_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]]  -datapath_only 5.0
set_property src_info {type:SCOPED_XDC file:4 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only  5.0
set_property src_info {type:SCOPED_XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]]  -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_v7_bd/axi_chip2chip_0/inst/m_axi_lite_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins axi_lite_slave_gen.reset_sync_lite_slv/sync_reset_out_reg/C] -to [get_pins axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/fifo_reset_reg/PRE] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins i_v7_bd/axi_chip2chip_0/inst/m_axi_lite_aclk]]]
