# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fifo_cdc_18b/fifo_cdc_18b.xci
# IP: The module: 'fifo_cdc_18b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/fifo_cdc_18b/fifo_cdc_18b/fifo_cdc_18b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_cdc_18b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: ip/fifo_cdc_18b/fifo_cdc_18b/fifo_cdc_18b.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_cdc_18b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: ip/fifo_cdc_18b/fifo_cdc_18b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_cdc_18b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: ip/fifo_cdc_18b/fifo_cdc_18b.xci
# IP: The module: 'fifo_cdc_18b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/fifo_cdc_18b/fifo_cdc_18b/fifo_cdc_18b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_cdc_18b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: ip/fifo_cdc_18b/fifo_cdc_18b/fifo_cdc_18b.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_cdc_18b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: ip/fifo_cdc_18b/fifo_cdc_18b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_cdc_18b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
